'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { API_URL } from '@/lib/api';
import { FileText, Search, Trash2, Eye, Download, Activity, Calendar, User } from 'lucide-react';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';
import { Input } from '@/components/ui/input';
import Link from 'next/link';

export default function AdminAssessmentsPage() {
  const [assessments, setAssessments] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  const fetchAssessments = async () => {
    try {
      const response = await fetch(`${API_URL}/admin/assessments`, {
        credentials: 'include',
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.message);
      setAssessments(data.assessments);
    } catch (error: any) {
      toast.error(error.message);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAssessments();
  }, []);

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this assessment?')) return;
    
    try {
      const response = await fetch(`${API_URL}/admin/assessments/${id}`, {
        method: 'DELETE',
        credentials: 'include',
      });
      if (!response.ok) throw new Error('Failed to delete assessment');
      toast.success('Assessment deleted successfully');
      setAssessments(assessments.filter(a => a.id !== id));
    } catch (error: any) {
      toast.error(error.message);
    }
  };

  const filteredAssessments = assessments.filter(a => 
    a.userId?.toLowerCase().includes(searchQuery.toLowerCase()) || 
    a.riskLevel?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-8 pb-20">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div className="space-y-2">
          <h1 className="text-4xl font-extrabold tracking-tight text-white">Master Assessment Feed</h1>
          <p className="text-muted-foreground text-lg font-medium">Review and manage all health assessments generated by the AI system.</p>
        </div>
        <div className="flex gap-4">
          <div className="relative w-full md:w-72 group">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
            <Input 
              placeholder="Search by ID or risk..." 
              className="pl-12 h-14 bg-white/5 border-white/10 rounded-2xl focus:ring-primary/20"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
          <Button 
            variant="outline" 
            onClick={() => window.open(`${API_URL}/admin/assessments/export`, '_blank')}
            className="rounded-2xl h-14 px-6 border-white/10 hover:bg-white/5 font-bold gap-2 hidden md:flex"
          >
            <Download className="h-5 w-5" /> Export CSV
          </Button>
        </div>
      </div>

      <div className="glass rounded-[2rem] border border-white/5 overflow-hidden shadow-2xl">
        <Table>
          <TableHeader className="bg-white/5">
            <TableRow className="hover:bg-transparent border-white/5">
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6 px-8">Assessment ID</TableHead>
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6">User Ref</TableHead>
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6 text-center">AI Risk Score</TableHead>
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6">Level</TableHead>
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6">Date</TableHead>
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6 px-8 text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              [...Array(5)].map((_, i) => (
                <TableRow key={i} className="border-white/5">
                  <TableCell colSpan={6} className="py-8 px-8"><div className="h-10 w-full bg-white/5 rounded-lg animate-pulse" /></TableCell>
                </TableRow>
              ))
            ) : filteredAssessments.length === 0 ? (
              <TableRow>
                <TableCell colSpan={6} className="py-20 text-center text-muted-foreground font-medium">
                  No assessments found.
                </TableCell>
              </TableRow>
            ) : filteredAssessments.map((a) => (
              <TableRow key={a.id} className="group hover:bg-white/5 border-white/5 transition-colors">
                <TableCell className="py-6 px-8 font-mono text-[11px] text-muted-foreground">
                  #{a.id.substring(0, 12)}
                </TableCell>
                <TableCell className="py-6">
                  <div className="flex items-center gap-2 text-sm font-bold text-white/90">
                    <User className="w-3.5 h-3.5 text-primary" />
                    {a.userId.substring(0, 8)}...
                  </div>
                </TableCell>
                <TableCell className="py-6 text-center">
                  <div className="inline-flex items-center justify-center w-10 h-10 rounded-xl bg-white/5 text-lg font-black text-white">
                    {a.riskScore}
                  </div>
                </TableCell>
                <TableCell className="py-6">
                  <Badge 
                    variant="outline" 
                    className={cn(
                      "text-[10px] uppercase font-black px-2 py-0 border-opacity-50",
                      a.riskLevel === 'high' ? 'border-destructive text-destructive bg-destructive/5' : 
                      a.riskLevel === 'moderate' ? 'border-amber-500 text-amber-500 bg-amber-500/5' : 
                      'border-emerald-500 text-emerald-500 bg-emerald-500/5'
                    )}
                  >
                    {a.riskLevel}
                  </Badge>
                </TableCell>
                <TableCell className="py-6 font-medium text-xs text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-3.5 h-3.5" />
                    {new Date(a.createdAt).toLocaleDateString()}
                  </div>
                </TableCell>
                <TableCell className="py-6 px-8 text-right">
                  <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-all duration-300 transform translate-x-2 group-hover:translate-x-0">
                    <Link href={`/results/${a.id}`}>
                      <Button variant="ghost" size="icon" className="rounded-xl hover:bg-primary/10 hover:text-primary">
                        <Eye className="w-5 h-5" />
                      </Button>
                    </Link>
                    <Button 
                      variant="ghost" 
                      size="icon" 
                      className="rounded-xl hover:bg-destructive/10 hover:text-destructive"
                      onClick={() => handleDelete(a.id)}
                    >
                      <Trash2 className="w-5 h-5" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
