'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { API_URL, fetchApi } from '@/lib/api';
import { FileText, Search, Trash2, Eye, Download, Activity, Calendar, User } from 'lucide-react';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';
import { Input } from '@/components/ui/input';
import Link from 'next/link';

export default function AdminAssessmentsPage() {
  const [assessments, setAssessments] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  const fetchAssessments = async () => {
    try {
      const data = await fetchApi('/admin/assessments');
      setAssessments(data.assessments);
    } catch (error: any) {
      toast.error(error.message);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAssessments();
  }, []);

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this assessment?')) return;
    
    try {
      await fetchApi(`/admin/assessments/${id}`, {
        method: 'DELETE',
      });
      toast.success('Assessment deleted successfully');
      setAssessments(assessments.filter(a => a.id !== id));
    } catch (error: any) {
      toast.error(error.message);
    }
  };

  const filteredAssessments = assessments.filter(a => 
    a.userId?.toLowerCase().includes(searchQuery.toLowerCase()) || 
    a.riskLevel?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-8 pb-20">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div className="space-y-2">
          <h1 className="text-4xl font-extrabold tracking-tight text-foreground">Master Assessment Feed</h1>
          <p className="text-muted-foreground text-lg font-medium">Review and manage all health assessments generated by the AI system.</p>
        </div>
        <div className="flex gap-4">
          <div className="relative w-full md:w-72 group">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
            <Input 
              placeholder="Search by ID or risk..." 
              className="pl-12 h-14 bg-muted/30 border-border/50 rounded-2xl focus:ring-primary/20"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
          <Button 
            variant="outline" 
            onClick={async () => {
              try {
                const res = await fetch(`${API_URL}/admin/assessments/export`, {
                  headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` },
                  credentials: 'include'
                });
                const blob = await res.blob();
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = 'assessments_export.csv';
                a.click();
              } catch (error) {
                toast.error("Failed to export data");
              }
            }}
            className="rounded-2xl h-14 px-6 border-border/50 hover:bg-muted font-bold gap-2 hidden md:flex"
          >
            <Download className="h-5 w-5" /> Export CSV
          </Button>
        </div>
      </div>

      <div className="glass rounded-[2rem] border border-border/50 overflow-x-auto shadow-2xl">
        <Table>
          <TableHeader className="bg-muted/30">
            <TableRow className="hover:bg-transparent border-border/50">
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6 px-8">Assessment ID</TableHead>
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6">Patient Info</TableHead>
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6 text-center">AI Risk Score</TableHead>
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6">Level</TableHead>
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6">Date</TableHead>
              <TableHead className="font-black uppercase tracking-widest text-[10px] py-6 px-8 text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              [...Array(5)].map((_, i) => (
                <TableRow key={i} className="border-border/50">
                  <TableCell colSpan={6} className="py-8 px-8"><div className="h-10 w-full bg-muted/50 rounded-lg animate-pulse" /></TableCell>
                </TableRow>
              ))
            ) : filteredAssessments.length === 0 ? (
              <TableRow>
                <TableCell colSpan={6} className="py-20 text-center text-muted-foreground font-medium">
                  No assessments found.
                </TableCell>
              </TableRow>
            ) : filteredAssessments.map((a) => (
              <TableRow key={a.id} className="group hover:bg-muted/50 border-border/50 transition-colors">
                <TableCell className="py-6 px-8 font-mono text-[11px] text-muted-foreground">
                  #{a.id.substring(0, 12)}
                </TableCell>
                <TableCell className="py-6">
                  <div className="flex flex-col">
                    <span className="text-sm font-bold text-foreground/90 flex items-center gap-2">
                      <User className="w-3.5 h-3.5 text-primary" />
                      {a.user?.name || "Unknown User"}
                    </span>
                    <span className="text-xs text-muted-foreground mt-1 uppercase tracking-widest font-black">
                      {a.personalData?.age ? `${a.personalData.age} Years Old` : "Age N/A"}
                    </span>
                  </div>
                </TableCell>
                <TableCell className="py-6 text-center">
                  <div className="inline-flex items-center justify-center w-10 h-10 rounded-xl bg-muted text-lg font-black text-foreground">
                    {a.riskScore}
                  </div>
                </TableCell>
                <TableCell className="py-6">
                  <Badge 
                    variant="outline" 
                    className={cn(
                      "text-[10px] uppercase font-black px-2 py-0 border-opacity-50",
                      a.riskLevel === 'high' ? 'border-destructive text-destructive bg-destructive/5' : 
                      a.riskLevel === 'moderate' ? 'border-amber-500 text-amber-500 bg-amber-500/5' : 
                      'border-emerald-500 text-emerald-500 bg-emerald-500/5'
                    )}
                  >
                    {a.riskLevel}
                  </Badge>
                </TableCell>
                <TableCell className="py-6 font-medium text-xs text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-3.5 h-3.5" />
                    {new Date(a.createdAt).toLocaleDateString()}
                  </div>
                </TableCell>
                <TableCell className="py-6 px-8 text-right">
                  <div className="flex items-center justify-end gap-2 transition-all duration-300">
                    <Link href={`/results/${a.id}`}>
                      <Button variant="ghost" size="icon" className="rounded-xl hover:bg-primary/10 hover:text-primary">
                        <Eye className="w-5 h-5" />
                      </Button>
                    </Link>
                    <Button 
                      variant="ghost" 
                      size="icon" 
                      className="rounded-xl hover:bg-destructive/10 hover:text-destructive"
                      onClick={() => handleDelete(a.id)}
                    >
                      <Trash2 className="w-5 h-5" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
